# https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml

loki:
  commonConfig:
    replication_factor: 2
  auth_enabled: false
  storage:
    bucketNames:
      # make sure the buckets have been create and their names are global unique
      chunks: <account_id>-loki-chunks
      ruler: <account_id>-loki-ruler
      admin: <account_id>-loki-admin
    type: "s3"
    s3:
      region: ap-southeast-2
      endpoint: "http://s3.ap-southeast-2.amazonaws.com"
singleBinary:
  replicas: 3
